version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: phoen_postgres
    restart: always
    environment:
      POSTGRES_USER: phoen
      POSTGRES_PASSWORD: phoenpassword
      POSTGRES_DB: phoendb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
