"""Initial schema

Revision ID: a9a80fbe79a9
Revises: 
Create Date: 2026-09-05 18:35:18.596421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9a80fbe79a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_chains',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('approval_level', sa.Integer(), nullable=True),
    sa.Column('role_name', sa.String(length=100), nullable=True),
    sa.Column('min_discount_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('max_discount_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('min_margin_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('approver_role', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_chains_id'), 'approval_chains', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('brands',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('support_level', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_id'), 'brands', ['id'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('tier', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('billing_address', sa.Text(), nullable=True),
    sa.Column('shipping_address', sa.Text(), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=True),
    sa.Column('account_manager', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('selling_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('min_margin_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('recurring', sa.Boolean(), nullable=True),
    sa.Column('billing_frequency', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('billing_frequency', sa.String(length=50), nullable=True),
    sa.Column('billing_interval', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('setup_fee', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('proration_enabled', sa.Boolean(), nullable=True),
    sa.Column('cancellation_policy', sa.Text(), nullable=True),
    sa.Column('refund_policy', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_subscription_plans_id'), 'subscription_plans', ['id'], unique=False)
    op.create_table('warehouses',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('warehouse_type', sa.String(length=50), nullable=True),
    sa.Column('manager_name', sa.String(length=100), nullable=True),
    sa.Column('capacity_units', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_warehouses_id'), 'warehouses', ['id'], unique=False)
    op.create_table('discount_rules',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('customer_tier', sa.String(length=50), nullable=True),
    sa.Column('category_id', sa.String(length=50), nullable=True),
    sa.Column('max_discount_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('min_margin_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('approval_level', sa.String(length=50), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discount_rules_id'), 'discount_rules', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand_id', sa.String(length=50), nullable=True),
    sa.Column('category_id', sa.String(length=50), nullable=True),
    sa.Column('subcategory_id', sa.String(length=50), nullable=True),
    sa.Column('product_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('manufacturer_part_number', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('base_cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('warranty_months', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('is_serialized', sa.Boolean(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['subcategory_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('quotations',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('quotation_number', sa.String(length=100), nullable=True),
    sa.Column('customer_id', sa.String(length=50), nullable=True),
    sa.Column('quotation_date', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('discount_total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tax_total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('grand_total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('approval_status', sa.String(length=50), nullable=True),
    sa.Column('deal_health', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quotation_number')
    )
    op.create_index(op.f('ix_quotations_id'), 'quotations', ['id'], unique=False)
    op.create_table('deal_health',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('quotation_id', sa.String(length=50), nullable=True),
    sa.Column('days_inactive', sa.Integer(), nullable=True),
    sa.Column('discount_anomaly_score', sa.Float(), nullable=True),
    sa.Column('delivery_risk_score', sa.Float(), nullable=True),
    sa.Column('approval_delay_score', sa.Float(), nullable=True),
    sa.Column('inventory_risk_score', sa.Float(), nullable=True),
    sa.Column('overall_health_score', sa.Float(), nullable=True),
    sa.Column('health_status', sa.String(length=50), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('last_evaluated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_health_id'), 'deal_health', ['id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('quotation_id', sa.String(length=50), nullable=True),
    sa.Column('customer_id', sa.String(length=50), nullable=True),
    sa.Column('invoice_date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('discount_total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tax_total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('grand_total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('billing_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('customer_po_number', sa.String(length=100), nullable=True),
    sa.Column('quotation_id', sa.String(length=50), nullable=True),
    sa.Column('customer_id', sa.String(length=50), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('grand_total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('primary_warehouse_id', sa.String(length=50), nullable=True),
    sa.Column('promised_delivery_date', sa.DateTime(), nullable=True),
    sa.Column('logistics_partner', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['primary_warehouse_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_table('product_recommendations',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('source_product_id', sa.String(length=50), nullable=True),
    sa.Column('recommended_product_id', sa.String(length=50), nullable=True),
    sa.Column('recommendation_type', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('co_purchase_rate', sa.Float(), nullable=True),
    sa.Column('margin_delta', sa.Float(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('promotion_active', sa.Boolean(), nullable=True),
    sa.Column('min_margin_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['recommended_product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['source_product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_recommendations_id'), 'product_recommendations', ['id'], unique=False)
    op.create_table('product_service_rules',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=True),
    sa.Column('service_id', sa.String(length=50), nullable=True),
    sa.Column('recommended', sa.Boolean(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_service_rules_id'), 'product_service_rules', ['id'], unique=False)
    op.create_table('product_variants',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('cpu', sa.String(length=100), nullable=True),
    sa.Column('ram', sa.String(length=100), nullable=True),
    sa.Column('storage', sa.String(length=100), nullable=True),
    sa.Column('storage_type', sa.String(length=50), nullable=True),
    sa.Column('gpu', sa.String(length=100), nullable=True),
    sa.Column('screen_size', sa.String(length=50), nullable=True),
    sa.Column('resolution', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('connectivity', sa.String(length=100), nullable=True),
    sa.Column('operating_system', sa.String(length=100), nullable=True),
    sa.Column('form_factor', sa.String(length=50), nullable=True),
    sa.Column('warranty_months', sa.Integer(), nullable=True),
    sa.Column('extra_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('selling_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_variants_id'), 'product_variants', ['id'], unique=False)
    op.create_index(op.f('ix_product_variants_sku'), 'product_variants', ['sku'], unique=True)
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.String(length=50), nullable=True),
    sa.Column('quotation_id', sa.String(length=50), nullable=True),
    sa.Column('plan_id', sa.String(length=50), nullable=True),
    sa.Column('plan_name', sa.String(length=255), nullable=True),
    sa.Column('annual_rate', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('billing_cycle', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('next_renewal_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('warehouse_id', sa.String(length=50), nullable=True),
    sa.Column('variant_id', sa.String(length=50), nullable=True),
    sa.Column('available_quantity', sa.Integer(), nullable=True),
    sa.Column('reserved_quantity', sa.Integer(), nullable=True),
    sa.Column('allocated_quantity', sa.Integer(), nullable=True),
    sa.Column('backorder_quantity', sa.Integer(), nullable=True),
    sa.Column('reorder_level', sa.Integer(), nullable=True),
    sa.Column('reorder_quantity', sa.Integer(), nullable=True),
    sa.Column('safety_stock', sa.Integer(), nullable=True),
    sa.Column('incoming_quantity', sa.Integer(), nullable=True),
    sa.Column('average_daily_demand', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('last_restocked_at', sa.DateTime(), nullable=True),
    sa.Column('next_expected_restock', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'variant_id', name='uix_warehouse_variant')
    )
    op.create_index(op.f('ix_inventory_id'), 'inventory', ['id'], unique=False)
    op.create_table('invoice_lines',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('invoice_id', sa.String(length=50), nullable=True),
    sa.Column('item_type', sa.String(length=50), nullable=True),
    sa.Column('variant_id', sa.String(length=50), nullable=True),
    sa.Column('service_id', sa.String(length=50), nullable=True),
    sa.Column('subscription_plan_id', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('line_total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('billing_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_lines_id'), 'invoice_lines', ['id'], unique=False)
    op.create_table('price_lists',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('customer_tier', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('variant_id', sa.String(length=50), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('minimum_quantity', sa.Integer(), nullable=True),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_lists_id'), 'price_lists', ['id'], unique=False)
    op.create_table('quotation_lines',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('quotation_id', sa.String(length=50), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('item_type', sa.String(length=50), nullable=True),
    sa.Column('variant_id', sa.String(length=50), nullable=True),
    sa.Column('service_id', sa.String(length=50), nullable=True),
    sa.Column('subscription_plan_id', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('line_total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('billing_type', sa.String(length=50), nullable=True),
    sa.Column('fulfillment_warehouse_id', sa.String(length=50), nullable=True),
    sa.Column('fulfillment_status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['fulfillment_warehouse_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotation_lines_id'), 'quotation_lines', ['id'], unique=False)
    op.create_table('customer_price_lists',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.String(length=50), nullable=True),
    sa.Column('price_list_id', sa.String(length=50), nullable=True),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['price_list_id'], ['price_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_price_lists_id'), 'customer_price_lists', ['id'], unique=False)
    op.create_table('negotiations',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('quotation_id', sa.String(length=50), nullable=True),
    sa.Column('customer_id', sa.String(length=50), nullable=True),
    sa.Column('quotation_line_id', sa.String(length=50), nullable=True),
    sa.Column('original_discount_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('requested_discount_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('customer_message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.ForeignKeyConstraint(['quotation_line_id'], ['quotation_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_negotiations_id'), 'negotiations', ['id'], unique=False)
    op.create_table('warehouse_allocations',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('quotation_id', sa.String(length=50), nullable=True),
    sa.Column('quotation_line_id', sa.String(length=50), nullable=True),
    sa.Column('variant_id', sa.String(length=50), nullable=True),
    sa.Column('warehouse_id', sa.String(length=50), nullable=True),
    sa.Column('allocated_quantity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('allocated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.ForeignKeyConstraint(['quotation_line_id'], ['quotation_lines.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_allocations_id'), 'warehouse_allocations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warehouse_allocations_id'), table_name='warehouse_allocations')
    op.drop_table('warehouse_allocations')
    op.drop_index(op.f('ix_negotiations_id'), table_name='negotiations')
    op.drop_table('negotiations')
    op.drop_index(op.f('ix_customer_price_lists_id'), table_name='customer_price_lists')
    op.drop_table('customer_price_lists')
    op.drop_index(op.f('ix_quotation_lines_id'), table_name='quotation_lines')
    op.drop_table('quotation_lines')
    op.drop_index(op.f('ix_price_lists_id'), table_name='price_lists')
    op.drop_table('price_lists')
    op.drop_index(op.f('ix_invoice_lines_id'), table_name='invoice_lines')
    op.drop_table('invoice_lines')
    op.drop_index(op.f('ix_inventory_id'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_product_variants_sku'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_id'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index(op.f('ix_product_service_rules_id'), table_name='product_service_rules')
    op.drop_table('product_service_rules')
    op.drop_index(op.f('ix_product_recommendations_id'), table_name='product_recommendations')
    op.drop_table('product_recommendations')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_deal_health_id'), table_name='deal_health')
    op.drop_table('deal_health')
    op.drop_index(op.f('ix_quotations_id'), table_name='quotations')
    op.drop_table('quotations')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_discount_rules_id'), table_name='discount_rules')
    op.drop_table('discount_rules')
    op.drop_index(op.f('ix_warehouses_id'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_subscription_plans_id'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_brands_id'), table_name='brands')
    op.drop_table('brands')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_approval_chains_id'), table_name='approval_chains')
    op.drop_table('approval_chains')
    # ### end Alembic commands ###
