"""
DealFlow360 Base Entities Builder — Mumbai Edition
Generates:
- 34 Enterprise IT Brands
- 18 Categories (4 Domains, 14 Subcategories)
- 5 Warehouses (Primary: MUM-DC-01, Secondary: NAVI-MUM-DC-01)
- 42 Professional IT Services
- 22 Recurring Subscription Plans
- 28 Discount Governance Rules
- 5 Approval Chains
- 100 Authentic Mumbai Enterprise Accounts (BKC, Nariman Point, Lower Parel, Andheri, Powai, Navi Mumbai)
"""

# 1. BRANDS (34 Global Enterprise Hardware & Software OEMs)
BRANDS = [
    ("BRD-001", "Dell Technologies", "DELL", "United States", "TIER_1_OEM", "ACTIVE"),
    ("BRD-002", "Hewlett Packard Enterprise", "HPE", "United States", "TIER_1_OEM", "ACTIVE"),
    ("BRD-003", "HP Inc.", "HP", "United States", "TIER_1_OEM", "ACTIVE"),
    ("BRD-004", "Lenovo Enterprise", "LENOVO", "Hong Kong", "TIER_1_OEM", "ACTIVE"),
    ("BRD-005", "Apple Inc.", "APPLE", "United States", "TIER_1_OEM", "ACTIVE"),
    ("BRD-006", "Cisco Systems", "CISCO", "United States", "TIER_1_OEM", "ACTIVE"),
    ("BRD-007", "Fortinet", "FORTINET", "United States", "TIER_1_OEM", "ACTIVE"),
    ("BRD-008", "Palo Alto Networks", "PALO_ALTO", "United States", "TIER_1_OEM", "ACTIVE"),
    ("BRD-009", "Aruba Networks", "ARUBA", "United States", "TIER_1_OEM", "ACTIVE"),
    ("BRD-010", "Ubiquiti Networks", "UBIQUITI", "United States", "TIER_2_OEM", "ACTIVE"),
    ("BRD-011", "Synology Inc.", "SYNOLOGY", "Taiwan", "TIER_1_OEM", "ACTIVE"),
    ("BRD-012", "QNAP Systems", "QNAP", "Taiwan", "TIER_1_OEM", "ACTIVE"),
    ("BRD-013", "Western Digital", "WD", "United States", "TIER_1_OEM", "ACTIVE"),
    ("BRD-014", "Seagate Technology", "SEAGATE", "United States", "TIER_1_OEM", "ACTIVE"),
    ("BRD-015", "Samsung Electronics", "SAMSUNG", "South Korea", "TIER_1_OEM", "ACTIVE"),
    ("BRD-016", "Kingston Technology", "KINGSTON", "United States", "TIER_2_OEM", "ACTIVE"),
    ("BRD-017", "LG Electronics", "LG", "South Korea", "TIER_1_OEM", "ACTIVE"),
    ("BRD-018", "ViewSonic", "VIEWSONIC", "United States", "TIER_2_OEM", "ACTIVE"),
    ("BRD-019", "ASUS Commercial", "ASUS", "Taiwan", "TIER_1_OEM", "ACTIVE"),
    ("BRD-020", "Acer Enterprise", "ACER", "Taiwan", "TIER_2_OEM", "ACTIVE"),
    ("BRD-021", "Microsoft Surface", "MICROSOFT", "United States", "TIER_1_OEM", "ACTIVE"),
    ("BRD-022", "Google Enterprise", "GOOGLE", "United States", "TIER_1_OEM", "ACTIVE"),
    ("BRD-023", "OnePlus Technology", "ONEPLUS", "China", "TIER_2_OEM", "ACTIVE"),
    ("BRD-024", "Motorola Business", "MOTOROLA", "United States", "TIER_2_OEM", "ACTIVE"),
    ("BRD-025", "Schneider Electric / APC", "APC", "France", "TIER_1_OEM", "ACTIVE"),
    ("BRD-026", "Eaton Corporation", "EATON", "Ireland", "TIER_1_OEM", "ACTIVE"),
    ("BRD-027", "Vertiv Holdings", "VERTIV", "United States", "TIER_1_OEM", "ACTIVE"),
    ("BRD-028", "Brother International", "BROTHER", "Japan", "TIER_2_OEM", "ACTIVE"),
    ("BRD-029", "Canon Inc.", "CANON", "Japan", "TIER_1_OEM", "ACTIVE"),
    ("BRD-030", "Epson Commercial", "EPSON", "Japan", "TIER_2_OEM", "ACTIVE"),
    ("BRD-031", "Logitech Enterprise", "LOGITECH", "Switzerland", "TIER_1_OEM", "ACTIVE"),
    ("BRD-032", "Poly (HP Poly)", "POLY", "United States", "TIER_1_OEM", "ACTIVE"),
    ("BRD-033", "Jabra GN", "JABRA", "Denmark", "TIER_1_OEM", "ACTIVE"),
    ("BRD-034", "Sophos Technologies", "SOPHOS", "United Kingdom", "TIER_1_OEM", "ACTIVE")
]

# 2. CATEGORIES (4 Root Domains, 14 Specialized Leaf Categories)
CATEGORIES = [
    # 4 Root Domains
    ("CAT-COMP", "Enterprise Computing Systems", "", "Commercial Laptops, Desktops, Financial Workstations and Servers", "ACTIVE"),
    ("CAT-INFRA", "Data Center & Network Infrastructure", "", "Enterprise Storage Arrays, Switches, Routers, and Firewalls", "ACTIVE"),
    ("CAT-WORK", "Workplace, Displays & Mobility", "", "Displays, Mobile Devices, Tablets, and Corporate Peripherals", "ACTIVE"),
    ("CAT-PWR", "Enterprise Power, Print & Collaboration", "", "Online UPS, Meeting Room Hardware, and Document Solutions", "ACTIVE"),

    # 14 Leaf Subcategories
    ("CAT-LAP", "Commercial & Executive Laptops", "CAT-COMP", "Enterprise ultrabooks, executive notebooks, and developer laptops", "ACTIVE"),
    ("CAT-DSK", "Enterprise Desktops & Mini PCs", "CAT-COMP", "Compact corporate desktops, micro form factors, and all-in-ones", "ACTIVE"),
    ("CAT-WKS", "Financial & Engineering Workstations", "CAT-COMP", "Multi-GPU trading workstations, CAD engineering, and AI compute", "ACTIVE"),
    ("CAT-SRV", "Enterprise Rack & Blade Servers", "CAT-COMP", "High-density compute, database servers, and virtualization nodes", "ACTIVE"),
    ("CAT-STO", "Enterprise SAN/NAS Storage Arrays", "CAT-INFRA", "All-flash SAN arrays, enterprise NAS, and high-capacity storage", "ACTIVE"),
    ("CAT-NET", "Enterprise Core & Access Networking", "CAT-INFRA", "Managed Layer 2/3 switches, PoE+ edge switches, and wireless APs", "ACTIVE"),
    ("CAT-SEC", "Cybersecurity & Perimeter Firewalls", "CAT-INFRA", "Next-Gen firewalls, secure SD-WAN, and threat defense appliances", "ACTIVE"),
    ("CAT-MON", "Financial Trading & Professional Displays", "CAT-WORK", "Multi-monitor trading screens, color-calibrated 4K, and ultrawide", "ACTIVE"),
    ("CAT-UPS", "Mission-Critical Online UPS", "CAT-PWR", "Online double-conversion UPS, rackmount batteries, and PDUs", "ACTIVE"),
    ("CAT-SMP", "Enterprise Smartphones & Mobility", "CAT-WORK", "Secure corporate mobile devices for executives and field operations", "ACTIVE"),
    ("CAT-TAB", "Enterprise Tablets", "CAT-WORK", "Rugged and commercial tablets for executive and audit workflows", "ACTIVE"),
    ("CAT-PRN", "Enterprise Document & Print Solutions", "CAT-PWR", "High-volume departmental laser printers and secure multifunction MFPs", "ACTIVE"),
    ("CAT-COL", "Corporate Video Collaboration", "CAT-PWR", "Boardroom video bars, conferencing bundles, and digital whiteboards", "ACTIVE"),
    ("CAT-ACC", "Enterprise Docks & Accessories", "CAT-WORK", "Thunderbolt docks, GaN fast chargers, headsets, and ergonomics", "ACTIVE")
]

# 3. WAREHOUSES (Primary: MUM-DC-01, Secondary: NAVI-MUM-DC-01)
WAREHOUSES = [
    ("WH-001", "MUM-DC-01", "Mumbai Enterprise Technology Distribution Center", "Mumbai", "Maharashtra", "India", "DISTRIBUTION_CENTER", "Vikramaditya Singhania", 180000, "ACTIVE"),
    ("WH-002", "NAVI-MUM-DC-01", "Navi Mumbai Logistics & Staging Hub", "Navi Mumbai", "Maharashtra", "India", "LOGISTICS_HUB", "Sunil Deshmukh", 100000, "ACTIVE"),
    ("WH-003", "BLR-DC-01", "Bangalore Central Technology Hub", "Bengaluru", "Karnataka", "India", "REGIONAL_HUB", "Kavita Sharma", 120000, "ACTIVE"),
    ("WH-004", "DEL-DC-01", "Delhi NCR Enterprise Logistics Center", "Gurugram", "Haryana", "India", "REGIONAL_HUB", "Rajiv Khanna", 90000, "ACTIVE"),
    ("WH-005", "AMD-DC-01", "Ahmedabad Commercial Distribution Center", "Ahmedabad", "Gujarat", "India", "REGIONAL_HUB", "Nilesh Patel", 60000, "ACTIVE")
]

# 4. SERVICES (42 Professional IT Services)
SERVICES = [
    ("SRV-001", "SRV-SRV-INST", "Enterprise Server & High-Density Rack Installation", "INSTALLATION", "Physical mounting, dual PDU cable management, and POST diagnostics", 5000.0, 8500.0, 18.0, 41.2, False, "ONE_TIME", "ACTIVE"),
    ("SRV-002", "SRV-STO-ZONE", "SAN/NAS Storage Array Commissioning & Zoning", "DEPLOYMENT", "LUN creation, RAID-6/10 initialization, and multipath Fibre Channel zoning", 9500.0, 16500.0, 18.0, 42.4, False, "ONE_TIME", "ACTIVE"),
    ("SRV-003", "SRV-NET-SWL3", "L2/L3 Core & Access Network Switch Configuration", "CONFIGURATION", "VLAN segmentation, 802.1Q trunking, OSPF/BGP routing, and storm control", 7000.0, 13500.0, 18.0, 48.1, False, "ONE_TIME", "ACTIVE"),
    ("SRV-004", "SRV-SEC-FWHA", "Next-Gen Firewall High-Availability Cluster Deployment", "SECURITY", "Active/Passive HA pairing, SSL deep inspection, and perimeter threat policy", 11000.0, 19500.0, 18.0, 43.6, False, "ONE_TIME", "ACTIVE"),
    ("SRV-005", "SRV-LAP-GOLD", "Enterprise Laptop Zero-Touch Imaging & Domain Join", "DEPLOYMENT", "Windows 11 Enterprise Autopilot provisioning, BitLocker encryption, CMDB enrollment", 750.0, 1400.0, 18.0, 46.4, False, "ONE_TIME", "ACTIVE"),
    ("SRV-006", "SRV-WKS-TRAD", "Financial Trading Desk Multi-Display & Workstation Setup", "DEPLOYMENT", "Quad-display monitor arm alignment, Bloomberg/Refinitiv terminal tuning", 1600.0, 3200.0, 18.0, 50.0, False, "ONE_TIME", "ACTIVE"),
    ("SRV-007", "SRV-CAB-P24", "Structured Cat6A 24-Port Patch Panel Termination", "CABLING", "Fluke DSX-8000 certified patch cabling, dressing, and labelling", 3800.0, 7200.0, 18.0, 47.2, False, "ONE_TIME", "ACTIVE"),
    ("SRV-008", "SRV-UPS-COMM", "Online Double-Conversion Rackmount UPS Commissioning", "ELECTRICAL", "Battery cold start calibration, external bypass panel wiring, SNMP alert setup", 2600.0, 5000.0, 18.0, 48.0, False, "ONE_TIME", "ACTIVE"),
    ("SRV-009", "SRV-COL-BRM", "Corporate Boardroom Video Conferencing Integration", "COLLABORATION", "Acoustic calibration, dual commercial display mounting, touch panel pairing", 8500.0, 15500.0, 18.0, 45.2, False, "ONE_TIME", "ACTIVE"),
    ("SRV-010", "SRV-AST-RFID", "Enterprise Asset Tagging & Tamper-Evident CMDB Enrollment", "MANAGED_SERVICE", "Metallic QR barcode affixing, serial logging, and ERP inventory sync", 200.0, 400.0, 18.0, 50.0, False, "ONE_TIME", "ACTIVE"),
    ("SRV-011", "SRV-MIG-DBDS", "Enterprise Data Migration & Database Storage Sync", "MIGRATION", "Hot replication, block-level migration, snapshot cutover, and integrity test", 6000.0, 11000.0, 18.0, 45.5, False, "ONE_TIME", "ACTIVE"),
    ("SRV-012", "SRV-EMG-4HR", "Emergency Mumbai Onsite 4-Hour Response IT Support", "SUPPORT", "Dedicated Tier-3 engineer dispatch for high-priority trading/DC incidents", 1800.0, 3500.0, 18.0, 48.6, False, "ONE_TIME", "ACTIVE"),
    ("SRV-013", "SRV-MAC-MDM", "Apple macOS Corporate Fleet Provisioning & Jamf Enrollment", "DEPLOYMENT", "Apple Business Manager (ABM) zero-touch enrollment, FileVault, and compliance", 900.0, 1600.0, 18.0, 43.8, False, "ONE_TIME", "ACTIVE"),
    ("SRV-014", "SRV-WIFI-SURV", "Enterprise Wi-Fi 6E Predictive RF Site Survey & Heatmap", "AUDIT", "Spectrum analysis, rogue AP detection, and optimal AP density design", 12000.0, 22000.0, 18.0, 45.5, False, "ONE_TIME", "ACTIVE"),
    ("SRV-015", "SRV-VM-DEPL", "VMware ESXi / Proxmox Virtualization Node Setup", "DEPLOYMENT", "Host hardening, vSwitch networking, iSCSI/NFS storage datastore creation", 6500.0, 12000.0, 18.0, 45.8, False, "ONE_TIME", "ACTIVE"),
    ("SRV-016", "SRV-DESK-DEPL", "Corporate Desktop & Micro-PC Desk-Side Rollout", "DEPLOYMENT", "Physical placement, peripheral hookup, secure cable conduit, and network testing", 600.0, 1100.0, 18.0, 45.5, False, "ONE_TIME", "ACTIVE"),
    ("SRV-017", "SRV-SW-MIG", "Core Switch Firmware Upgrade & High-Availability Test", "MAINTENANCE", "Non-disruptive ISSU upgrade, redundant supervisor failover verification", 8000.0, 14500.0, 18.0, 44.8, False, "ONE_TIME", "ACTIVE"),
    ("SRV-018", "SRV-FW-AUD", "Firewall Rulebase Audit & BFSI Compliance Hardening", "AUDIT", "Shadow rule removal, PCI-DSS / RBI compliance verification, audit logging", 15000.0, 26000.0, 18.0, 42.3, False, "ONE_TIME", "ACTIVE"),
    ("SRV-019", "SRV-PRN-SEC", "Secure Pull-Printing & Departmental Badge Reader Setup", "DEPLOYMENT", "AD/LDAP user authentication, card reader integration, print quota limits", 2500.0, 4800.0, 18.0, 47.9, False, "ONE_TIME", "ACTIVE"),
    ("SRV-020", "SRV-BACK-VER", "Automated Backup Validation & Disaster Recovery Drill", "SECURITY", "Bare-metal restore test, immutable snapshot verification, RTO/RPO report", 10000.0, 18000.0, 18.0, 44.4, False, "ONE_TIME", "ACTIVE"),
    ("SRV-021", "SRV-OPT-100G", "High-Speed 40G/100G Optical Transceiver Link Validation", "NETWORK", "OTDR fiber insertion loss testing, transceiver light level verification", 4500.0, 8500.0, 18.0, 47.1, False, "ONE_TIME", "ACTIVE"),
    ("SRV-022", "SRV-RACK-REOR", "Datacenter Rack Re-organization & Cable Remanagement", "FACILITY", "Cold-aisle containment dressing, color-coded patch cord restructuring", 7500.0, 13500.0, 18.0, 44.4, False, "ONE_TIME", "ACTIVE"),
    ("SRV-023", "SRV-SAN-TUNE", "All-Flash SAN Array IOPS Tuning & Host Multipath Config", "STORAGE", "Queue depth optimization, ALUA multipath policy, tiering performance test", 8500.0, 15000.0, 18.0, 43.3, False, "ONE_TIME", "ACTIVE"),
    ("SRV-024", "SRV-MOB-KNOX", "Samsung Knox Enterprise Mobility Policy Enrollment", "MOBILITY", "Secure workspace containerization, remote wipe policy, and kiosk lock", 450.0, 850.0, 18.0, 47.1, False, "ONE_TIME", "ACTIVE"),
    ("SRV-025", "SRV-DISP-CAL", "UltraSharp Color Grading Display Factory-Grade Calibration", "DISPLAY", "Hardware LUT colorimeter calibration (sRGB, DCI-P3, Rec. 709 profiling)", 900.0, 1800.0, 18.0, 50.0, False, "ONE_TIME", "ACTIVE"),
    ("SRV-026", "SRV-UPS-BATT", "UPS Hot-Swappable Battery Replacement & Load Bank Test", "ELECTRICAL", "Battery module swap, load test under 80% capacity, discharge calibration", 3200.0, 6000.0, 18.0, 46.7, False, "ONE_TIME", "ACTIVE"),
    ("SRV-027", "SRV-CYB-EDR", "Enterprise EDR Endpoint Security Agent Mass Rollout", "SECURITY", "CrowdStrike / Defender for Endpoint silent push, sensor health validation", 350.0, 700.0, 18.0, 50.0, False, "ONE_TIME", "ACTIVE"),
    ("SRV-028", "SRV-TEL-CONF", "Executive Desk VoIP Phone Configuration & QoS Mapping", "TELECOM", "SIP extension registration, PoE switch voice VLAN, jitter buffer optimization", 650.0, 1200.0, 18.0, 45.8, False, "ONE_TIME", "ACTIVE"),
    ("SRV-029", "SRV-DOCK-FIRM", "Thunderbolt Docking Station Mass Firmware Harmonization", "MAINTENANCE", "DisplayPort/USB-C controller firmware flashing, docking reliability patch", 400.0, 750.0, 18.0, 46.7, False, "ONE_TIME", "ACTIVE"),
    ("SRV-030", "SRV-NAS-REPL", "Cross-Site Branch NAS Automated Replication Setup", "STORAGE", "Rsync/Btrfs snapshot scheduling, bandwidth throttling, failover testing", 4500.0, 8500.0, 18.0, 47.1, False, "ONE_TIME", "ACTIVE"),
    ("SRV-031", "SRV-AV-TUNE", "Meeting Room Acoustic Echo Cancellation & Mic Array Tuning", "COLLABORATION", "Reverberation dampening, beamforming mic polar pattern calibration", 4000.0, 7500.0, 18.0, 46.7, False, "ONE_TIME", "ACTIVE"),
    ("SRV-032", "SRV-BIOS-LOCK", "Corporate BIOS/UEFI Security Lock & TPM 2.0 Hardening", "SECURITY", "Custom supervisor password, secure boot enforcement, port lockout", 300.0, 600.0, 18.0, 50.0, False, "ONE_TIME", "ACTIVE"),
    ("SRV-033", "SRV-ENV-MON", "Server Room Thermal & Humidity Sensor Integration", "FACILITY", "SNMP environmental probe deployment, SMS/Email temperature threshold alerts", 2800.0, 5200.0, 18.0, 46.2, False, "ONE_TIME", "ACTIVE"),
    ("SRV-034", "SRV-HDD-SHRED", "On-Site Cryptographic Hard Drive Decommissioning & Shred", "SECURITY", "NIST 800-88 sanitization, degaussing, certificate of destruction issue", 450.0, 900.0, 18.0, 50.0, False, "ONE_TIME", "ACTIVE"),
    ("SRV-035", "SRV-EX-ONBRD", "Executive White-Glove VIP User IT Onboarding Experience", "SUPPORT", "In-person concierge orientation, multi-device sync, personalized hotline", 2500.0, 5000.0, 18.0, 50.0, False, "ONE_TIME", "ACTIVE"),
    ("SRV-036", "SRV-NOC-TKT", "Remote NOC Technical Support Incident Token (5-Pack)", "SUPPORT", "Pack of 5 priority remote remediation tickets with 15-min SLA", 3000.0, 5800.0, 18.0, 48.3, False, "ONE_TIME", "ACTIVE"),
    ("SRV-037", "SRV-PDU-INST", "Intelligent Metered/Switched PDU Integration", "ELECTRICAL", "Phase balancing, branch circuit power telemetry, remote outlet reboot", 2200.0, 4200.0, 18.0, 47.6, False, "ONE_TIME", "ACTIVE"),
    ("SRV-038", "SRV-FIB-SPLC", "Single-Mode Fiber Optic Fusion Splicing & OTDR Test", "CABLING", "LC duplex fiber core fusion splicing, heat-shrink sleeve, attenuation log", 6000.0, 11500.0, 18.0, 47.8, False, "ONE_TIME", "ACTIVE"),
    ("SRV-039", "SRV-RAD-SRV", "Enterprise 802.1X Network Access Control (NAC) RADIUS", "SECURITY", "EAP-TLS certificate authentication, dynamic VLAN steering, guest portal", 9000.0, 16500.0, 18.0, 45.5, False, "ONE_TIME", "ACTIVE"),
    ("SRV-040", "SRV-TAB-KIOSK", "Commercial Tablet Kiosk Mount & POS Lockdown Setup", "MOBILITY", "Vandal-resistant enclosure mounting, kiosk application pinning, PoE split", 1200.0, 2400.0, 18.0, 50.0, False, "ONE_TIME", "ACTIVE"),
    ("SRV-041", "SRV-AUD-POW", "Data Center Clean Power Quality & Harmonic Distortion Audit", "AUDIT", "Total Harmonic Distortion (THD) logging, ground loop detection", 14000.0, 25000.0, 18.0, 44.0, False, "ONE_TIME", "ACTIVE"),
    ("SRV-042", "SRV-RELOC-IT", "Enterprise Inter-Facility Server Rack Relocation & Re-rack", "LOGISTICS", "De-cabling, shock-absorbing transport, re-racking, and cold boot support", 18000.0, 32000.0, 18.0, 43.8, False, "ONE_TIME", "ACTIVE")
]

# 5. SUBSCRIPTION PLANS (22 Recurring Managed Plans)
SUBSCRIPTION_PLANS = [
    ("SUB-001", "AMC-ENT-24X7", "Comprehensive 24x7 4-Hour SLA Enterprise Hardware AMC", "YEARLY", 12, 52000.0, 5000.0, True, "30_DAYS_NOTICE", "PRORATED", "ACTIVE"),
    ("SUB-002", "AMC-TRAD-IMM", "Mission-Critical Trading Floor 1-Hour Immediate Response AMC", "YEARLY", 12, 85000.0, 7500.0, True, "30_DAYS_NOTICE", "NO_REFUND", "ACTIVE"),
    ("SUB-003", "AMC-NBD-STD", "Next-Business-Day (NBD) Standard On-Site Hardware AMC", "YEARLY", 12, 24000.0, 2500.0, True, "30_DAYS_NOTICE", "PRORATED", "ACTIVE"),
    ("SUB-004", "AMC-SVR-PLAT", "Platinum Datacenter Server Cluster AMC with Spares Onsite", "YEARLY", 12, 110000.0, 10000.0, True, "60_DAYS_NOTICE", "PRORATED", "ACTIVE"),
    ("SUB-005", "NOC-SW-MON", "Cloud Network Operations Center (NOC) Managed Switch Care", "MONTHLY", 1, 1950.0, 1200.0, True, "IMMEDIATE", "PRORATED", "ACTIVE"),
    ("SUB-006", "SOC-FW-MGD", "Managed Firewall Security Operations (SOC) & Threat Feeds", "MONTHLY", 1, 9200.0, 3000.0, True, "30_DAYS_NOTICE", "PRORATED", "ACTIVE"),
    ("SUB-007", "MDM-SEAT-ANN", "Cloud Endpoint Mobility Management (MDM) Enterprise Seat", "YEARLY", 12, 2600.0, 500.0, True, "30_DAYS_NOTICE", "NO_REFUND", "ACTIVE"),
    ("SUB-008", "MDM-VIP-EXEC", "Executive VIP Concierge Mobility Protection & Lost Device SLA", "YEARLY", 12, 5400.0, 1000.0, True, "30_DAYS_NOTICE", "PRORATED", "ACTIVE"),
    ("SUB-009", "SAN-STOR-MON", "Proactive All-Flash SAN Storage Telemetry & Capacity Planning", "MONTHLY", 1, 4200.0, 2000.0, True, "30_DAYS_NOTICE", "PRORATED", "ACTIVE"),
    ("SUB-010", "AV-ROOM-MGD", "Corporate Boardroom AV & Collaboration Managed Service", "MONTHLY", 1, 4600.0, 2500.0, True, "30_DAYS_NOTICE", "PRORATED", "ACTIVE"),
    ("SUB-011", "BAAS-CLD-1TB", "Managed Immutable Cloud Backup & Ransomware Vault (1TB)", "MONTHLY", 1, 2800.0, 1500.0, True, "IMMEDIATE", "PRORATED", "ACTIVE"),
    ("SUB-012", "BAAS-CLD-10TB", "Enterprise Datacenter Immutable Cloud Backup (10TB Pool)", "MONTHLY", 1, 22000.0, 5000.0, True, "30_DAYS_NOTICE", "PRORATED", "ACTIVE"),
    ("SUB-013", "DESK-SEAT-SUP", "Enterprise Desk-Side Support & SLA Helpdesk (Per User)", "MONTHLY", 1, 750.0, 500.0, True, "30_DAYS_NOTICE", "PRORATED", "ACTIVE"),
    ("SUB-014", "WIFI-MGD-AP", "Managed Cloud Wi-Fi Access Point & Guest Portal Service", "MONTHLY", 1, 650.0, 500.0, True, "IMMEDIATE", "PRORATED", "ACTIVE"),
    ("SUB-015", "EDR-MGD-EP", "Managed Threat Hunting & EDR Endpoint Protection Seat", "YEARLY", 12, 3200.0, 500.0, True, "30_DAYS_NOTICE", "NO_REFUND", "ACTIVE"),
    ("SUB-016", "UPS-BATT-CARE", "UPS Battery Health Assurance & Annual Replacement Program", "YEARLY", 12, 14500.0, 2000.0, True, "30_DAYS_NOTICE", "PRORATED", "ACTIVE"),
    ("SUB-017", "PRN-MGD-MPS", "Managed Print Services & Automated Toner Replenishment", "MONTHLY", 1, 3500.0, 1500.0, True, "30_DAYS_NOTICE", "PRORATED", "ACTIVE"),
    ("SUB-018", "SIEM-LOG-BFSI", "BFSI Compliant Immutable Log Retention & Audit Archival", "MONTHLY", 1, 16000.0, 5000.0, True, "60_DAYS_NOTICE", "NO_REFUND", "ACTIVE"),
    ("SUB-019", "DNS-SEC-PRO", "Enterprise Protective DNS & Anti-Phishing Security Shield", "YEARLY", 12, 1800.0, 500.0, True, "IMMEDIATE", "NO_REFUND", "ACTIVE"),
    ("SUB-020", "DR-HOT-STAND", "Hot-Standby Virtual Machine Compute Replication Seat", "MONTHLY", 1, 7800.0, 3000.0, True, "30_DAYS_NOTICE", "PRORATED", "ACTIVE"),
    ("SUB-021", "MAC-JAMF-PRO", "Jamf Pro Hosted MDM Subscription & Apple Enterprise Care", "YEARLY", 12, 3600.0, 600.0, True, "30_DAYS_NOTICE", "NO_REFUND", "ACTIVE"),
    ("SUB-022", "NET-AUTO-SDN", "Software-Defined Network Fabric Orchestration & Telemetry", "MONTHLY", 1, 6200.0, 2500.0, True, "30_DAYS_NOTICE", "PRORATED", "ACTIVE")
]

# 6. DISCOUNT RULES (28 Rules governing Tiers, Category Ceilings, Margin Floors & Approvals)
DISCOUNT_RULES = [
    # Standard Tier
    ("DR-001", "Standard", "CAT-LAP", 8.0, 16.0, "L0_AUTO", "LOW", True),
    ("DR-002", "Standard", "CAT-DSK", 8.0, 16.0, "L0_AUTO", "LOW", True),
    ("DR-003", "Standard", "CAT-WKS", 7.0, 17.0, "L0_AUTO", "LOW", True),
    ("DR-004", "Standard", "CAT-SRV", 6.0, 18.0, "L0_AUTO", "LOW", True),
    ("DR-005", "Standard", "CAT-STO", 6.0, 18.0, "L0_AUTO", "LOW", True),
    ("DR-006", "Standard", "CAT-NET", 7.0, 17.0, "L0_AUTO", "LOW", True),
    ("DR-007", "Standard", "CAT-SEC", 6.0, 18.0, "L0_AUTO", "LOW", True),

    # SMB Tier
    ("DR-008", "SMB", "CAT-LAP", 12.0, 13.0, "L1_SALES_MANAGER", "LOW", True),
    ("DR-009", "SMB", "CAT-DSK", 12.0, 13.0, "L1_SALES_MANAGER", "LOW", True),
    ("DR-010", "SMB", "CAT-WKS", 10.0, 14.0, "L1_SALES_MANAGER", "MEDIUM", True),
    ("DR-011", "SMB", "CAT-SRV", 9.0, 15.0, "L1_SALES_MANAGER", "MEDIUM", True),
    ("DR-012", "SMB", "CAT-STO", 9.0, 15.0, "L1_SALES_MANAGER", "MEDIUM", True),
    ("DR-013", "SMB", "CAT-NET", 10.0, 14.0, "L1_SALES_MANAGER", "LOW", True),
    ("DR-014", "SMB", "CAT-SEC", 9.0, 15.0, "L1_SALES_MANAGER", "MEDIUM", True),

    # Enterprise Tier
    ("DR-015", "Enterprise", "CAT-LAP", 16.0, 10.0, "L2_FINANCE_DIRECTOR", "MEDIUM", True),
    ("DR-016", "Enterprise", "CAT-DSK", 16.0, 10.0, "L2_FINANCE_DIRECTOR", "MEDIUM", True),
    ("DR-017", "Enterprise", "CAT-WKS", 14.0, 11.0, "L2_FINANCE_DIRECTOR", "HIGH", True),
    ("DR-018", "Enterprise", "CAT-SRV", 13.0, 12.0, "L2_FINANCE_DIRECTOR", "HIGH", True),
    ("DR-019", "Enterprise", "CAT-STO", 13.0, 12.0, "L2_FINANCE_DIRECTOR", "HIGH", True),
    ("DR-020", "Enterprise", "CAT-NET", 14.0, 11.0, "L2_FINANCE_DIRECTOR", "MEDIUM", True),
    ("DR-021", "Enterprise", "CAT-SEC", 13.0, 12.0, "L2_FINANCE_DIRECTOR", "HIGH", True),

    # Strategic Global Partner Tier
    ("DR-022", "Strategic", "CAT-LAP", 22.0, 8.0, "L3_COMMERCIAL_VP", "CRITICAL", True),
    ("DR-023", "Strategic", "CAT-DSK", 22.0, 8.0, "L3_COMMERCIAL_VP", "CRITICAL", True),
    ("DR-024", "Strategic", "CAT-WKS", 19.0, 9.0, "L3_COMMERCIAL_VP", "CRITICAL", True),
    ("DR-025", "Strategic", "CAT-SRV", 17.0, 10.0, "L3_COMMERCIAL_VP", "CRITICAL", True),
    ("DR-026", "Strategic", "CAT-STO", 17.0, 10.0, "L3_COMMERCIAL_VP", "CRITICAL", True),
    ("DR-027", "Strategic", "CAT-NET", 19.0, 9.0, "L3_COMMERCIAL_VP", "CRITICAL", True),
    ("DR-028", "Strategic", "CAT-SEC", 17.0, 10.0, "L3_COMMERCIAL_VP", "CRITICAL", True)
]

# 7. APPROVAL CHAINS (5-tier Escalation Matrix)
APPROVAL_CHAINS = [
    ("AC-001", "L0_AUTO", "Standard Auto-Approval", 0.0, 8.0, 15.0, "None", "Quote within pre-approved sales rep threshold"),
    ("AC-002", "L1_SALES_MANAGER", "Regional Sales Manager Review", 8.1, 13.0, 12.0, "Sales Manager", "Discounts exceeding standard baseline up to 13.0%"),
    ("AC-003", "L2_FINANCE_DIRECTOR", "Commercial Finance Review", 13.1, 17.0, 10.0, "Finance Director", "Significant enterprise concession requiring gross margin validation"),
    ("AC-004", "L3_COMMERCIAL_VP", "Commercial VP & Country Head Approval", 17.1, 22.0, 8.0, "Commercial VP", "Large strategic account concession with multi-year volume commitments"),
    ("AC-005", "L4_EXECUTIVE_BOARD", "Executive Board Special Approval", 22.1, 35.0, 5.0, "Executive Committee", "Exceptional mega-deal discount below standard enterprise margin floor")
]

# 8. 100 AUTHENTIC MUMBAI ENTERPRISE CUSTOMER ACCOUNTS
# Financial Services, Brokerages, Corporate HQs, Media, Pharma, Logistics, Tech across Mumbai Corridors
CUSTOMERS_DATA = [
    # Strategic Accounts (10 Accounts)
    ("CUST-001", "MUM-CORP-001", "Meridian Capital Financial Services Ltd", "BFSI - Investment Banking", "Strategic", "Mumbai", "Maharashtra", "India",
     "Tower 2, Floor 22, One International Centre, Senapati Bapat Marg, Lower Parel, Mumbai 400013",
     "Tower 2, Floor 22, One International Centre, Senapati Bapat Marg, Lower Parel, Mumbai 400013",
     35000000.0, 60, "Aditya Birla", "ACTIVE"),
    ("CUST-002", "MUM-CORP-002", "WestBay Securities & Algorithmic Trading Ltd", "BFSI - Stock Brokerage", "Strategic", "Mumbai", "Maharashtra", "India",
     "Plot C-66, G Block, Bandra-Kurla Complex, Bandra East, Mumbai 400051",
     "Plot C-66, G Block, Bandra-Kurla Complex, Bandra East, Mumbai 400051",
     40000000.0, 60, "Rohan Mehra", "ACTIVE"),
    ("CUST-003", "MUM-CORP-003", "HarborPoint Life Insurance Corporation Ltd", "BFSI - Insurance", "Strategic", "Mumbai", "Maharashtra", "India",
     "Maker Chambers VI, Nariman Point, Mumbai 400021",
     "Maker Chambers VI, Nariman Point, Mumbai 400021",
     45000000.0, 90, "Pooja Desai", "ACTIVE"),
    ("CUST-004", "MUM-CORP-004", "Skyline Pharmaceuticals Global R&D Ltd", "Pharmaceuticals", "Strategic", "Mumbai", "Maharashtra", "India",
     "Nirlon Knowledge Park, Western Express Highway, Goregaon East, Mumbai 400063",
     "Nirlon Knowledge Park, Western Express Highway, Goregaon East, Mumbai 400063",
     38000000.0, 60, "Siddharth Nair", "ACTIVE"),
    ("CUST-005", "MUM-CORP-005", "BluePeak Media Broadcasting Network Pvt Ltd", "Media & Entertainment", "Strategic", "Mumbai", "Maharashtra", "India",
     "Trade World, D-Wing, Kamala Mills Compound, Lower Parel, Mumbai 400013",
     "Trade World, D-Wing, Kamala Mills Compound, Lower Parel, Mumbai 400013",
     30000000.0, 45, "Vikramaditya Singhania", "ACTIVE"),
    ("CUST-006", "MUM-CORP-006", "MetroCore Global Logistics & Supply Chain Ltd", "Logistics & Maritime", "Strategic", "Mumbai", "Maharashtra", "India",
     "Navi Mumbai SEZ Gateway, Sector 11, CBD Belapur, Navi Mumbai 400614",
     "Navi Mumbai SEZ Gateway, Sector 11, CBD Belapur, Navi Mumbai 400614",
     32000000.0, 60, "Sunil Deshmukh", "ACTIVE"),
    ("CUST-007", "MUM-CORP-007", "Crestline Management Consulting International", "Professional Services", "Strategic", "Mumbai", "Maharashtra", "India",
     "Platina, Bandra-Kurla Complex, Bandra East, Mumbai 400051",
     "Platina, Bandra-Kurla Complex, Bandra East, Mumbai 400051",
     28000000.0, 45, "Aditya Birla", "ACTIVE"),
    ("CUST-008", "MUM-CORP-008", "UrbanGrid Retail & E-Commerce Technologies Ltd", "Retail & E-Commerce", "Strategic", "Mumbai", "Maharashtra", "India",
     "Lodha Excelus, Apollo Mills Compound, NM Joshi Marg, Mahalaxmi, Mumbai 400011",
     "Lodha Excelus, Apollo Mills Compound, NM Joshi Marg, Mahalaxmi, Mumbai 400011",
     35000000.0, 60, "Rohan Mehra", "ACTIVE"),
    ("CUST-009", "MUM-CORP-009", "Coastal Healthcare & Hospital Networks Ltd", "Healthcare & Life Sciences", "Strategic", "Mumbai", "Maharashtra", "India",
     "Dr. Annie Besant Road, Worli, Mumbai 400018",
     "Dr. Annie Besant Road, Worli, Mumbai 400018",
     32000000.0, 60, "Pooja Desai", "ACTIVE"),
    ("CUST-010", "MUM-CORP-010", "ApexFin Derivative Clearing House Corporation", "BFSI - Market Infrastructure", "Strategic", "Mumbai", "Maharashtra", "India",
     "Exchange Plaza, Bandra-Kurla Complex, Bandra East, Mumbai 400051",
     "Exchange Plaza, Bandra-Kurla Complex, Bandra East, Mumbai 400051",
     50000000.0, 90, "Vikramaditya Singhania", "ACTIVE"),

    # Enterprise Accounts (40 Accounts: CUST-011 to CUST-050)
    ("CUST-011", "MUM-CORP-011", "Vanguard TradeFin Solutions Ltd", "BFSI - Trade Finance", "Enterprise", "Mumbai", "Maharashtra", "India",
     "Mafatlal Centre, 8th Floor, Vidhan Bhavan Marg, Nariman Point, Mumbai 400021",
     "Mafatlal Centre, 8th Floor, Vidhan Bhavan Marg, Nariman Point, Mumbai 400021",
     15000000.0, 45, "Siddharth Nair", "ACTIVE"),
    ("CUST-012", "MUM-CORP-012", "Imperial Maritime Shipping & Tankers Ltd", "Logistics & Maritime", "Enterprise", "Mumbai", "Maharashtra", "India",
     "Ballard Estate, Fort, Mumbai 400001",
     "Ballard Estate, Fort, Mumbai 400001",
     18000000.0, 60, "Sunil Deshmukh", "ACTIVE"),
    ("CUST-013", "MUM-CORP-013", "Omicron Asset Management Advisory Ltd", "BFSI - Wealth Management", "Enterprise", "Mumbai", "Maharashtra", "India",
     "Kaledonia, Sahar Road, Andheri East, Mumbai 400069",
     "Kaledonia, Sahar Road, Andheri East, Mumbai 400069",
     12000000.0, 45, "Aditya Birla", "ACTIVE"),
    ("CUST-014", "MUM-CORP-014", "Novartis Discovery Labs Western India", "Pharmaceuticals", "Enterprise", "Mumbai", "Maharashtra", "India",
     "Hiranandani Business Park, Powai, Mumbai 400076",
     "Hiranandani Business Park, Powai, Mumbai 400076",
     22000000.0, 60, "Pooja Desai", "ACTIVE"),
    ("CUST-015", "MUM-CORP-015", "Citadel Reinsurance Underwriters Ltd", "BFSI - Insurance", "Enterprise", "Mumbai", "Maharashtra", "India",
     "BKC One, Bandra-Kurla Complex, Mumbai 400051",
     "BKC One, Bandra-Kurla Complex, Mumbai 400051",
     25000000.0, 60, "Rohan Mehra", "ACTIVE"),
    ("CUST-016", "MUM-CORP-016", "Trident Hospitality & Luxury Resorts Ltd", "Hospitality", "Enterprise", "Mumbai", "Maharashtra", "India",
     "Nariman Point Waterfront, Mumbai 400021",
     "Nariman Point Waterfront, Mumbai 400021",
     14000000.0, 45, "Vikramaditya Singhania", "ACTIVE"),
    ("CUST-017", "MUM-CORP-017", "Prism Interactive Advertising Network", "Media & Advertising", "Enterprise", "Mumbai", "Maharashtra", "India",
     "Famous Cine Building, Dr. E Moses Road, Mahalaxmi, Mumbai 400011",
     "Famous Cine Building, Dr. E Moses Road, Mahalaxmi, Mumbai 400011",
     11000000.0, 45, "Siddharth Nair", "ACTIVE"),
    ("CUST-018", "MUM-CORP-018", "Equinox Quantitative Trading Technologies", "BFSI - FinTech", "Enterprise", "Mumbai", "Maharashtra", "India",
     "IL&FS Financial Centre, BKC, Bandra East, Mumbai 400051",
     "IL&FS Financial Centre, BKC, Bandra East, Mumbai 400051",
     20000000.0, 45, "Aditya Birla", "ACTIVE"),
    ("CUST-019", "MUM-CORP-019", "Zenith Legal Advisors & Solictors LLP", "Legal Services", "Enterprise", "Mumbai", "Maharashtra", "India",
     "Express Towers, 14th Floor, Nariman Point, Mumbai 400021",
     "Express Towers, 14th Floor, Nariman Point, Mumbai 400021",
     9000000.0, 30, "Pooja Desai", "ACTIVE"),
    ("CUST-020", "MUM-CORP-020", "Aura Consumer Goods FMCG Holdings Ltd", "Manufacturing - FMCG", "Enterprise", "Mumbai", "Maharashtra", "India",
     "Peninsula Business Park, Tower A, Lower Parel, Mumbai 400013",
     "Peninsula Business Park, Tower A, Lower Parel, Mumbai 400013",
     19000000.0, 60, "Rohan Mehra", "ACTIVE"),
    ("CUST-021", "MUM-CORP-021", "Falcon Aviation & Charter Services Ltd", "Aviation & Logistics", "Enterprise", "Mumbai", "Maharashtra", "India",
     "Chhatrapati Shivaji Maharaj International Airport T2 Terminal Road, Sahar, Mumbai 400099",
     "Chhatrapati Shivaji Maharaj International Airport T2 Terminal Road, Sahar, Mumbai 400099",
     16000000.0, 45, "Sunil Deshmukh", "ACTIVE"),
    ("CUST-022", "MUM-CORP-022", "Reliance PetroChem Trading International", "Energy & Chemicals", "Enterprise", "Mumbai", "Maharashtra", "India",
     "Maker Chambers IV, Nariman Point, Mumbai 400021",
     "Maker Chambers IV, Nariman Point, Mumbai 400021",
     24000000.0, 60, "Vikramaditya Singhania", "ACTIVE"),
    ("CUST-023", "MUM-CORP-023", "Pinnacle Real Estate Developers Ltd", "Real Estate & Infrastructure", "Enterprise", "Mumbai", "Maharashtra", "India",
     "Indiabulls Finance Centre, Tower 1, Elphinstone Road, Mumbai 400013",
     "Indiabulls Finance Centre, Tower 1, Elphinstone Road, Mumbai 400013",
     17000000.0, 45, "Siddharth Nair", "ACTIVE"),
    ("CUST-024", "MUM-CORP-024", "Starlight Film Studios & Digital VFX Ltd", "Media & Entertainment", "Enterprise", "Mumbai", "Maharashtra", "India",
     "Film City Complex, Goregaon East, Mumbai 400065",
     "Film City Complex, Goregaon East, Mumbai 400065",
     13000000.0, 45, "Aditya Birla", "ACTIVE"),
    ("CUST-025", "MUM-CORP-025", "Lumina Diagnostics & Genomic Labs", "Healthcare", "Enterprise", "Mumbai", "Maharashtra", "India",
     "MIDC Central Road, Andheri East, Mumbai 400093",
     "MIDC Central Road, Andheri East, Mumbai 400093",
     14000000.0, 45, "Pooja Desai", "ACTIVE"),
    ("CUST-026", "MUM-CORP-026", "Goldcrest Bullion & Commodity Traders", "BFSI - Commodities", "Enterprise", "Mumbai", "Maharashtra", "India",
     "Zaveri Bazaar Commercial Towers, Kalbadevi, Mumbai 400002",
     "Zaveri Bazaar Commercial Towers, Kalbadevi, Mumbai 400002",
     16000000.0, 30, "Rohan Mehra", "ACTIVE"),
    ("CUST-027", "MUM-CORP-027", "Mahindra Auto Component Design Labs", "Manufacturing - Automotive", "Enterprise", "Mumbai", "Maharashtra", "India",
     "Akurli Road, Kandivali East, Mumbai 400101",
     "Akurli Road, Kandivali East, Mumbai 400101",
     18000000.0, 60, "Sunil Deshmukh", "ACTIVE"),
    ("CUST-028", "MUM-CORP-028", "Sterling Microfinance Bank Ltd", "BFSI - Banking", "Enterprise", "Mumbai", "Maharashtra", "India",
     "Free Press House, Free Press Journal Marg, Nariman Point, Mumbai 400021",
     "Free Press House, Free Press Journal Marg, Nariman Point, Mumbai 400021",
     21000000.0, 60, "Vikramaditya Singhania", "ACTIVE"),
    ("CUST-029", "MUM-CORP-029", "Quantum Pay Gateway Solutions Ltd", "BFSI - FinTech", "Enterprise", "Mumbai", "Maharashtra", "India",
     "Supreme Business Park, B-Wing, Hiranandani Gardens, Powai, Mumbai 400076",
     "Supreme Business Park, B-Wing, Hiranandani Gardens, Powai, Mumbai 400076",
     19000000.0, 45, "Aditya Birla", "ACTIVE"),
    ("CUST-030", "MUM-CORP-030", "Tata Consumer Brands Global HQ", "Manufacturing - FMCG", "Enterprise", "Mumbai", "Maharashtra", "India",
     "Bombay House, 24 Homi Mody Street, Fort, Mumbai 400001",
     "Bombay House, 24 Homi Mody Street, Fort, Mumbai 400001",
     26000000.0, 60, "Siddharth Nair", "ACTIVE"),
    ("CUST-031", "MUM-CORP-031", "Bombay Freight Forwarders Consortium", "Logistics", "Enterprise", "Mumbai", "Maharashtra", "India",
     "JNPT Port Logistics Corridor, Dronagiri, Navi Mumbai 400707",
     "JNPT Port Logistics Corridor, Dronagiri, Navi Mumbai 400707",
     12000000.0, 45, "Sunil Deshmukh", "ACTIVE"),
    ("CUST-032", "MUM-CORP-032", "Oberoi Luxury Residential Estates Ltd", "Real Estate", "Enterprise", "Mumbai", "Maharashtra", "India",
     "Commerz II, International Business Park, Oberoi Garden City, Goregaon East, Mumbai 400063",
     "Commerz II, International Business Park, Oberoi Garden City, Goregaon East, Mumbai 400063",
     15000000.0, 45, "Pooja Desai", "ACTIVE"),
    ("CUST-033", "MUM-CORP-033", "Aura Health Insurance TPA Services", "BFSI - Insurance", "Enterprise", "Mumbai", "Maharashtra", "India",
     "Mindspace, Building No 3, Malad West, Mumbai 400064",
     "Mindspace, Building No 3, Malad West, Mumbai 400064",
     13500000.0, 45, "Rohan Mehra", "ACTIVE"),
    ("CUST-034", "MUM-CORP-034", "SunGard Financial Technology Labs", "Technology - FinTech", "Enterprise", "Mumbai", "Maharashtra", "India",
     "Nesco IT Park, Western Express Highway, Goregaon East, Mumbai 400063",
     "Nesco IT Park, Western Express Highway, Goregaon East, Mumbai 400063",
     17500000.0, 45, "Vikramaditya Singhania", "ACTIVE"),
    ("CUST-035", "MUM-CORP-035", "Navi Mumbai Data Center Co-location Ltd", "Data Center / Infrastructure", "Enterprise", "Mumbai", "Maharashtra", "India",
     "TTC Industrial Area, MIDC, Mahape, Navi Mumbai 400710",
     "TTC Industrial Area, MIDC, Mahape, Navi Mumbai 400710",
     28000000.0, 60, "Sunil Deshmukh", "ACTIVE"),
    ("CUST-036", "MUM-CORP-036", "Castrol Industrial Lubricants India", "Manufacturing", "Enterprise", "Mumbai", "Maharashtra", "India",
     "Techniplex I, Veer Savarkar Flyover, Goregaon West, Mumbai 400062",
     "Techniplex I, Veer Savarkar Flyover, Goregaon West, Mumbai 400062",
     14000000.0, 45, "Siddharth Nair", "ACTIVE"),
    ("CUST-037", "MUM-CORP-037", "Global Wealth Family Office Advisors", "BFSI - Wealth Management", "Enterprise", "Mumbai", "Maharashtra", "India",
     "Bandra Kurla Complex, G Block, BKC, Mumbai 400051",
     "Bandra Kurla Complex, G Block, BKC, Mumbai 400051",
     16000000.0, 45, "Aditya Birla", "ACTIVE"),
    ("CUST-038", "MUM-CORP-038", "Cipla Respiratory Formulations Unit", "Pharmaceuticals", "Enterprise", "Mumbai", "Maharashtra", "India",
     "Cipla House, Peninsula Business Park, Lower Parel, Mumbai 400013",
     "Cipla House, Peninsula Business Park, Lower Parel, Mumbai 400013",
     20000000.0, 60, "Pooja Desai", "ACTIVE"),
    ("CUST-039", "MUM-CORP-039", "Star Television Content Studios", "Media & Entertainment", "Enterprise", "Mumbai", "Maharashtra", "India",
     "Urmi Estate, 95 Ganpatrao Kadam Marg, Lower Parel, Mumbai 400013",
     "Urmi Estate, 95 Ganpatrao Kadam Marg, Lower Parel, Mumbai 400013",
     15500000.0, 45, "Rohan Mehra", "ACTIVE"),
    ("CUST-040", "MUM-CORP-040", "BlueDart Express National Staging Hub", "Logistics", "Enterprise", "Mumbai", "Maharashtra", "India",
     "Blue Dart Centre, Sahar Airport Road, Andheri East, Mumbai 400099",
     "Blue Dart Centre, Sahar Airport Road, Andheri East, Mumbai 400099",
     19000000.0, 45, "Sunil Deshmukh", "ACTIVE"),
    ("CUST-041", "MUM-CORP-041", "Larsen & Toubro Heavy Engineering HQ", "Engineering & Construction", "Enterprise", "Mumbai", "Maharashtra", "India",
     "L&T House, Ballard Estate, Mumbai 400001",
     "L&T House, Ballard Estate, Mumbai 400001",
     25000000.0, 60, "Vikramaditya Singhania", "ACTIVE"),
    ("CUST-042", "MUM-CORP-042", "Godrej Consumer Products Global", "Manufacturing - FMCG", "Enterprise", "Mumbai", "Maharashtra", "India",
     "Godrej One, Pirojshanagar, Eastern Express Highway, Vikhroli East, Mumbai 400079",
     "Godrej One, Pirojshanagar, Eastern Express Highway, Vikhroli East, Mumbai 400079",
     22000000.0, 60, "Siddharth Nair", "ACTIVE"),
    ("CUST-043", "MUM-CORP-043", "Kotak Private Equity & Venture Partners", "BFSI - Private Equity", "Enterprise", "Mumbai", "Maharashtra", "India",
     "27 BKC, C-27, G Block, Bandra Kurla Complex, Mumbai 400051",
     "27 BKC, C-27, G Block, Bandra Kurla Complex, Mumbai 400051",
     24000000.0, 60, "Aditya Birla", "ACTIVE"),
    ("CUST-044", "MUM-CORP-044", "Hindalco Metal Trading Division", "Metals & Mining", "Enterprise", "Mumbai", "Maharashtra", "India",
     "Ahura Centre, B-Wing, Mahakali Caves Road, Andheri East, Mumbai 400093",
     "Ahura Centre, B-Wing, Mahakali Caves Road, Andheri East, Mumbai 400093",
     16500000.0, 45, "Rohan Mehra", "ACTIVE"),
    ("CUST-045", "MUM-CORP-045", "Edelweiss Capital Institutional Equities", "BFSI - Brokerage", "Enterprise", "Mumbai", "Maharashtra", "India",
     "Edelweiss House, Off CST Road, Kalina, Santacruz East, Mumbai 400098",
     "Edelweiss House, Off CST Road, Kalina, Santacruz East, Mumbai 400098",
     18500000.0, 45, "Pooja Desai", "ACTIVE"),
    ("CUST-046", "MUM-CORP-046", "Piramal Pharma Solutions Corporate", "Pharmaceuticals", "Enterprise", "Mumbai", "Maharashtra", "India",
     "Piramal Ananta, Agastya Corporate Park, Kurla West, Mumbai 400070",
     "Piramal Ananta, Agastya Corporate Park, Kurla West, Mumbai 400070",
     21000000.0, 60, "Vikramaditya Singhania", "ACTIVE"),
    ("CUST-047", "MUM-CORP-047", "Tata Memorial Cancer Care Clinical IT", "Healthcare", "Enterprise", "Mumbai", "Maharashtra", "India",
     "Dr. E Borges Road, Parel, Mumbai 400012",
     "Dr. E Borges Road, Parel, Mumbai 400012",
     14500000.0, 45, "Siddharth Nair", "ACTIVE"),
    ("CUST-048", "MUM-CORP-048", "Bennett Coleman & Co Media Technologies", "Media & Publishing", "Enterprise", "Mumbai", "Maharashtra", "India",
     "Times of India Building, Dr. DN Road, Fort, Mumbai 400001",
     "Times of India Building, Dr. DN Road, Fort, Mumbai 400001",
     17000000.0, 45, "Rohan Mehra", "ACTIVE"),
    ("CUST-049", "MUM-CORP-049", "Allcargo Multi-Modal Logistics Hub", "Logistics", "Enterprise", "Mumbai", "Maharashtra", "India",
     "Allcargo House, CST Road, Kalina, Santacruz East, Mumbai 400098",
     "Allcargo House, CST Road, Kalina, Santacruz East, Mumbai 400098",
     15500000.0, 45, "Sunil Deshmukh", "ACTIVE"),
    ("CUST-050", "MUM-CORP-050", "Taj Luxury Hotels & Hospitality Group", "Hospitality", "Enterprise", "Mumbai", "Maharashtra", "India",
     "Apollo Bunder, Colaba, Mumbai 400001",
     "Apollo Bunder, Colaba, Mumbai 400001",
     16000000.0, 45, "Aditya Birla", "ACTIVE"),

    # SMB Accounts (30 Accounts: CUST-051 to CUST-080)
    ("CUST-051", "MUM-CORP-051", "FinTech Nexus Payment Gateway LLP", "FinTech", "SMB", "Mumbai", "Maharashtra", "India",
     "Trade Star Building, Andheri-Kurla Road, Andheri East, Mumbai 400059",
     "Trade Star Building, Andheri-Kurla Road, Andheri East, Mumbai 400059",
     4500000.0, 30, "Aditya Birla", "ACTIVE"),
    ("CUST-052", "MUM-CORP-052", "MarineLine Customs Clearing Agency", "Logistics", "SMB", "Mumbai", "Maharashtra", "India",
     "Wavell House, Graham Road, Ballard Estate, Mumbai 400001",
     "Wavell House, Graham Road, Ballard Estate, Mumbai 400001",
     3500000.0, 30, "Sunil Deshmukh", "ACTIVE"),
    ("CUST-053", "MUM-CORP-053", "Boutique Wealth Advisory Partners", "Wealth Management", "SMB", "Mumbai", "Maharashtra", "India",
     "Raheja Chambers, Free Press Journal Marg, Nariman Point, Mumbai 400021",
     "Raheja Chambers, Free Press Journal Marg, Nariman Point, Mumbai 400021",
     5000000.0, 30, "Pooja Desai", "ACTIVE"),
    ("CUST-054", "MUM-CORP-054", "Powai AI Algorithmic Analytics Labs", "SaaS & AI", "SMB", "Mumbai", "Maharashtra", "India",
     "Ventura Building, Hiranandani Business Park, Powai, Mumbai 400076",
     "Ventura Building, Hiranandani Business Park, Powai, Mumbai 400076",
     6000000.0, 30, "Rohan Mehra", "ACTIVE"),
    ("CUST-055", "MUM-CORP-055", "Colaba Capital Seed Ventures", "Venture Capital", "SMB", "Mumbai", "Maharashtra", "India",
     "Waterfield Road, Bandra West, Mumbai 400050",
     "Waterfield Road, Bandra West, Mumbai 400050",
     4000000.0, 30, "Aditya Birla", "ACTIVE"),
    ("CUST-056", "MUM-CORP-056", "Apex Pharma Formulations Thane", "Pharma", "SMB", "Mumbai", "Maharashtra", "India",
     "Wagle Industrial Estate, Road No 16, Thane West, Maharashtra 400604",
     "Wagle Industrial Estate, Road No 16, Thane West, Maharashtra 400604",
     5500000.0, 30, "Pooja Desai", "ACTIVE"),
    ("CUST-057", "MUM-CORP-057", "Khar Digital Advertising & Branding Studio", "Advertising", "SMB", "Mumbai", "Maharashtra", "India",
     "Linking Road, Khar West, Mumbai 400052",
     "Linking Road, Khar West, Mumbai 400052",
     3000000.0, 15, "Siddharth Nair", "ACTIVE"),
    ("CUST-058", "MUM-CORP-058", "Navi Mumbai Cold Storage Logistics", "Logistics", "SMB", "Mumbai", "Maharashtra", "India",
     "APMC Market Yard II, Turbhe, Navi Mumbai 400705",
     "APMC Market Yard II, Turbhe, Navi Mumbai 400705",
     4200000.0, 30, "Sunil Deshmukh", "ACTIVE"),
    ("CUST-059", "MUM-CORP-059", "Malabar Hill Legal Consultants", "Legal", "SMB", "Mumbai", "Maharashtra", "India",
     "Mittal Tower, B Wing, Nariman Point, Mumbai 400021",
     "Mittal Tower, B Wing, Nariman Point, Mumbai 400021",
     3800000.0, 30, "Aditya Birla", "ACTIVE"),
    ("CUST-060", "MUM-CORP-060", "Bandra Boutique Hospitality Suites", "Hospitality", "SMB", "Mumbai", "Maharashtra", "India",
     "Turner Road, Bandra West, Mumbai 400050",
     "Turner Road, Bandra West, Mumbai 400050",
     3200000.0, 15, "Rohan Mehra", "ACTIVE"),
    ("CUST-061", "MUM-CORP-061", "Goregaon Animation & Gaming Works", "Gaming & Animation", "SMB", "Mumbai", "Maharashtra", "India",
     "Lotus Corporate Park, Laxmi Nagar, Goregaon East, Mumbai 400063",
     "Lotus Corporate Park, Laxmi Nagar, Goregaon East, Mumbai 400063",
     4800000.0, 30, "Siddharth Nair", "ACTIVE"),
    ("CUST-062", "MUM-CORP-062", "Thane Precision Auto Machining", "Manufacturing", "SMB", "Mumbai", "Maharashtra", "India",
     "Pokhran Road No 2, Majiwada, Thane West 400601",
     "Pokhran Road No 2, Majiwada, Thane West 400601",
     3600000.0, 30, "Sunil Deshmukh", "ACTIVE"),
    ("CUST-063", "MUM-CORP-063", "Sahar Airport Freight Clearance LLP", "Logistics", "SMB", "Mumbai", "Maharashtra", "India",
     "IAAI Cargo Complex, Sahar, Andheri East, Mumbai 400099",
     "IAAI Cargo Complex, Sahar, Andheri East, Mumbai 400099",
     2800000.0, 15, "Sunil Deshmukh", "ACTIVE"),
    ("CUST-064", "MUM-CORP-064", "Juhu Beach Event Management Partners", "Media & Events", "SMB", "Mumbai", "Maharashtra", "India",
     "JVPD Scheme, 10th Road, Juhu, Mumbai 400049",
     "JVPD Scheme, 10th Road, Juhu, Mumbai 400049",
     2500000.0, 15, "Rohan Mehra", "ACTIVE"),
    ("CUST-065", "MUM-CORP-065", "Chembur Diagnostics & Pathology Lab", "Healthcare", "SMB", "Mumbai", "Maharashtra", "India",
     "Sion-Trombay Road, Chembur, Mumbai 400071",
     "Sion-Trombay Road, Chembur, Mumbai 400071",
     3400000.0, 30, "Pooja Desai", "ACTIVE"),
    ("CUST-066", "MUM-CORP-066", "Vashi Retail Electronics Distribution", "Retail", "SMB", "Mumbai", "Maharashtra", "India",
     "Sector 17, Vashi, Navi Mumbai 400703",
     "Sector 17, Vashi, Navi Mumbai 400703",
     4600000.0, 30, "Sunil Deshmukh", "ACTIVE"),
    ("CUST-067", "MUM-CORP-067", "Lower Parel Creative Architecture Studio", "Architecture & Design", "SMB", "Mumbai", "Maharashtra", "India",
     "Mathuradas Mills Compound, Senapati Bapat Marg, Lower Parel, Mumbai 400013",
     "Mathuradas Mills Compound, Senapati Bapat Marg, Lower Parel, Mumbai 400013",
     3200000.0, 30, "Siddharth Nair", "ACTIVE"),
    ("CUST-068", "MUM-CORP-068", "Ghatkopar Paper & Packaging Traders", "Packaging", "SMB", "Mumbai", "Maharashtra", "India",
     "LBS Marg, Ghatkopar West, Mumbai 400086",
     "LBS Marg, Ghatkopar West, Mumbai 400086",
     2900000.0, 15, "Rohan Mehra", "ACTIVE"),
    ("CUST-069", "MUM-CORP-069", "Dadar Commercial Offset Printers LLP", "Printing & Publishing", "SMB", "Mumbai", "Maharashtra", "India",
     "Ranade Road, Dadar West, Mumbai 400028",
     "Ranade Road, Dadar West, Mumbai 400028",
     3100000.0, 15, "Aditya Birla", "ACTIVE"),
    ("CUST-070", "MUM-CORP-070", "Andheri Telemarketing & BPO Hub", "BPO & Customer Care", "SMB", "Mumbai", "Maharashtra", "India",
     "Chakala, Andheri-Ghatkopar Link Road, Andheri East, Mumbai 400093",
     "Chakala, Andheri-Ghatkopar Link Road, Andheri East, Mumbai 400093",
     5200000.0, 30, "Vikramaditya Singhania", "ACTIVE"),
    ("CUST-071", "MUM-CORP-071", "Worli Point Boutique PR & Communications", "Public Relations", "SMB", "Mumbai", "Maharashtra", "India",
     "Poonam Chambers, B Wing, Shivsagar Estate, Worli, Mumbai 400018",
     "Poonam Chambers, B Wing, Shivsagar Estate, Worli, Mumbai 400018",
     2700000.0, 15, "Pooja Desai", "ACTIVE"),
    ("CUST-072", "MUM-CORP-072", "Kalyan Regional Bulk Distributors", "FMCG Distribution", "SMB", "Mumbai", "Maharashtra", "India",
     "APMC Complex, Kalyan West, Maharashtra 421301",
     "APMC Complex, Kalyan West, Maharashtra 421301",
     3800000.0, 30, "Sunil Deshmukh", "ACTIVE"),
    ("CUST-073", "MUM-CORP-073", "Santacruz Diamond Cutting & Export LLP", "Gem & Jewellery", "SMB", "Mumbai", "Maharashtra", "India",
     "Bharat Diamond Bourse, BKC, Bandra East, Mumbai 400051",
     "Bharat Diamond Bourse, BKC, Bandra East, Mumbai 400051",
     6500000.0, 30, "Rohan Mehra", "ACTIVE"),
    ("CUST-074", "MUM-CORP-074", "Mahim Bay Educational Coaching Network", "Education", "SMB", "Mumbai", "Maharashtra", "India",
     "Lady Jamshedji Road, Mahim West, Mumbai 400016",
     "Lady Jamshedji Road, Mahim West, Mumbai 400016",
     2200000.0, 15, "Aditya Birla", "ACTIVE"),
    ("CUST-075", "MUM-CORP-075", "Airoli Cloud Microservices Development", "IT Services", "SMB", "Mumbai", "Maharashtra", "India",
     "Reliable Tech Park, Thane-Belapur Road, Airoli, Navi Mumbai 400708",
     "Reliable Tech Park, Thane-Belapur Road, Airoli, Navi Mumbai 400708",
     5800000.0, 30, "Sunil Deshmukh", "ACTIVE"),
    ("CUST-076", "MUM-CORP-076", "Borivali Engineering Consulting Associates", "Engineering", "SMB", "Mumbai", "Maharashtra", "India",
     "SV Road, Borivali West, Mumbai 400092",
     "SV Road, Borivali West, Mumbai 400092",
     2600000.0, 15, "Siddharth Nair", "ACTIVE"),
    ("CUST-077", "MUM-CORP-077", "Mulund Clean Energy & Solar Solutions", "Renewables", "SMB", "Mumbai", "Maharashtra", "India",
     "Nehru Road, Mulund West, Mumbai 400080",
     "Nehru Road, Mulund West, Mumbai 400080",
     3900000.0, 30, "Rohan Mehra", "ACTIVE"),
    ("CUST-078", "MUM-CORP-078", "Mazgaon Marine Equipment Repair Yard", "Shipbuilding & Marine", "SMB", "Mumbai", "Maharashtra", "India",
     "Dockyard Road, Mazgaon, Mumbai 400010",
     "Dockyard Road, Mazgaon, Mumbai 400010",
     4100000.0, 30, "Sunil Deshmukh", "ACTIVE"),
    ("CUST-079", "MUM-CORP-079", "Girgaon Cultural Event Broadcasting Co", "Media", "SMB", "Mumbai", "Maharashtra", "India",
     "Opera House Commercial Chambers, Charni Road, Mumbai 400004",
     "Opera House Commercial Chambers, Charni Road, Mumbai 400004",
     2300000.0, 15, "Pooja Desai", "ACTIVE"),
    ("CUST-080", "MUM-CORP-080", "Kanjurmarg Optical Telecom Installers", "Telecom", "SMB", "Mumbai", "Maharashtra", "India",
     "LBS Marg, Kanjurmarg West, Mumbai 400078",
     "LBS Marg, Kanjurmarg West, Mumbai 400078",
     4700000.0, 30, "Aditya Birla", "ACTIVE"),

    # Standard Accounts (20 Accounts: CUST-081 to CUST-100)
    ("CUST-081", "MUM-CORP-081", "Tardeo Commercial Printing & Graphics", "Printing", "Standard", "Mumbai", "Maharashtra", "India",
     "AC Market Building, Tardeo Road, Mumbai 400034",
     "AC Market Building, Tardeo Road, Mumbai 400034",
     800000.0, 15, "Aditya Birla", "ACTIVE"),
    ("CUST-082", "MUM-CORP-082", "Sion Local Area Network Installers", "IT Support", "Standard", "Mumbai", "Maharashtra", "India",
     "Sion East Market, Mumbai 400022",
     "Sion East Market, Mumbai 400022",
     650000.0, 15, "Siddharth Nair", "ACTIVE"),
    ("CUST-083", "MUM-CORP-083", "Charni Road Tax & Audit Services", "Accounting", "Standard", "Mumbai", "Maharashtra", "India",
     "Raja Ram Mohan Roy Road, Prarthana Samaj, Charni Road, Mumbai 400004",
     "Raja Ram Mohan Roy Road, Prarthana Samaj, Charni Road, Mumbai 400004",
     900000.0, 15, "Pooja Desai", "ACTIVE"),
    ("CUST-084", "MUM-CORP-084", "Kurla Auto Spares Wholesale Hub", "Automotive", "Standard", "Mumbai", "Maharashtra", "India",
     "SG Barve Marg, Kurla West, Mumbai 400070",
     "SG Barve Marg, Kurla West, Mumbai 400070",
     750000.0, 15, "Rohan Mehra", "ACTIVE"),
    ("CUST-085", "MUM-CORP-085", "Kandivali Medical Supply Distributors", "Healthcare", "Standard", "Mumbai", "Maharashtra", "India",
     "Mathuradas Road, Kandivali West, Mumbai 400067",
     "Mathuradas Road, Kandivali West, Mumbai 400067",
     1100000.0, 30, "Pooja Desai", "ACTIVE"),
    ("CUST-086", "MUM-CORP-086", "Bhandup Light Engineering Works", "Engineering", "Standard", "Mumbai", "Maharashtra", "India",
     "LBS Marg, Bhandup West, Mumbai 400078",
     "LBS Marg, Bhandup West, Mumbai 400078",
     850000.0, 15, "Sunil Deshmukh", "ACTIVE"),
    ("CUST-087", "MUM-CORP-087", "Vile Parle Commerce Tutoring Centre", "Education", "Standard", "Mumbai", "Maharashtra", "India",
     "Subhash Road, Vile Parle East, Mumbai 400057",
     "Subhash Road, Vile Parle East, Mumbai 400057",
     500000.0, 15, "Aditya Birla", "ACTIVE"),
    ("CUST-088", "MUM-CORP-088", "Byculla Textile Export Brokers", "Textiles", "Standard", "Mumbai", "Maharashtra", "India",
     "Dr. Babasaheb Ambedkar Road, Byculla, Mumbai 400027",
     "Dr. Babasaheb Ambedkar Road, Byculla, Mumbai 400027",
     950000.0, 15, "Rohan Mehra", "ACTIVE"),
    ("CUST-089", "MUM-CORP-089", "Malad Hardware & Electrical Stores", "Retail", "Standard", "Mumbai", "Maharashtra", "India",
     "Marve Road, Malad West, Mumbai 400064",
     "Marve Road, Malad West, Mumbai 400064",
     600000.0, 15, "Siddharth Nair", "ACTIVE"),
    ("CUST-090", "MUM-CORP-090", "Mira Road Office Stationery Mart", "Retail", "Standard", "Mumbai", "Maharashtra", "India",
     "Shanti Nagar, Mira Road East, Thane 401107",
     "Shanti Nagar, Mira Road East, Thane 401107",
     450000.0, 15, "Rohan Mehra", "ACTIVE"),
    ("CUST-091", "MUM-CORP-091", "Ghansoli Telecom Infrastructure Techs", "Telecom", "Standard", "Mumbai", "Maharashtra", "India",
     "Sector 3, Ghansoli, Navi Mumbai 400701",
     "Sector 3, Ghansoli, Navi Mumbai 400701",
     1000000.0, 15, "Sunil Deshmukh", "ACTIVE"),
    ("CUST-092", "MUM-CORP-092", "Dombivli Chemical Analytical Lab", "Chemicals", "Standard", "Mumbai", "Maharashtra", "India",
     "MIDC Phase II, Dombivli East, Maharashtra 421204",
     "MIDC Phase II, Dombivli East, Maharashtra 421204",
     700000.0, 15, "Pooja Desai", "ACTIVE"),
    ("CUST-093", "MUM-CORP-093", "Sewri Timber & Marine Plywood Mart", "Building Materials", "Standard", "Mumbai", "Maharashtra", "India",
     "Zakaria Bunder Road, Sewri West, Mumbai 400015",
     "Zakaria Bunder Road, Sewri West, Mumbai 400015",
     550000.0, 15, "Rohan Mehra", "ACTIVE"),
    ("CUST-094", "MUM-CORP-094", "Santacruz Courier & Cargo Hub", "Logistics", "Standard", "Mumbai", "Maharashtra", "India",
     "Nehru Road, Santacruz East, Mumbai 400055",
     "Nehru Road, Santacruz East, Mumbai 400055",
     800000.0, 15, "Sunil Deshmukh", "ACTIVE"),
    ("CUST-095", "MUM-CORP-095", "Wadala Freight Dispatch Operators", "Logistics", "Standard", "Mumbai", "Maharashtra", "India",
     "Truck Terminal Complex, Wadala East, Mumbai 400037",
     "Truck Terminal Complex, Wadala East, Mumbai 400037",
     900000.0, 15, "Sunil Deshmukh", "ACTIVE"),
    ("CUST-096", "MUM-CORP-096", "Vasai Light Precision Fabricators", "Manufacturing", "Standard", "Mumbai", "Maharashtra", "India",
     "Navghar Industrial Estate, Vasai East, Maharashtra 401210",
     "Navghar Industrial Estate, Vasai East, Maharashtra 401210",
     850000.0, 15, "Siddharth Nair", "ACTIVE"),
    ("CUST-097", "MUM-CORP-097", "Panvel Agro Trading Corporation", "Agriculture", "Standard", "Mumbai", "Maharashtra", "India",
     "Old Panvel Market, Panvel, Navi Mumbai 410206",
     "Old Panvel Market, Panvel, Navi Mumbai 410206",
     600000.0, 15, "Sunil Deshmukh", "ACTIVE"),
    ("CUST-098", "MUM-CORP-098", "Grant Road Computer Components Mart", "IT Retail", "Standard", "Mumbai", "Maharashtra", "India",
     "Lamington Road, Grant Road East, Mumbai 400007",
     "Lamington Road, Grant Road East, Mumbai 400007",
     1200000.0, 15, "Rohan Mehra", "ACTIVE"),
    ("CUST-099", "MUM-CORP-099", "Ulhasnagar Consumer Electronics Store", "Retail", "Standard", "Mumbai", "Maharashtra", "India",
     "Station Road, Ulhasnagar, Maharashtra 421002",
     "Station Road, Ulhasnagar, Maharashtra 421002",
     500000.0, 15, "Aditya Birla", "ACTIVE"),
    ("CUST-100", "MUM-CORP-100", "Belapur Coastal Security Hardware LLP", "Security Hardware", "Standard", "Mumbai", "Maharashtra", "India",
     "Sector 15, CBD Belapur, Navi Mumbai 400614",
     "Sector 15, CBD Belapur, Navi Mumbai 400614",
     950000.0, 15, "Sunil Deshmukh", "ACTIVE")
]

if __name__ == "__main__":
    print(f"Loaded {len(BRANDS)} Brands.")
    print(f"Loaded {len(CATEGORIES)} Categories.")
    print(f"Loaded {len(WAREHOUSES)} Warehouses.")
    print(f"Loaded {len(SERVICES)} Professional IT Services.")
    print(f"Loaded {len(SUBSCRIPTION_PLANS)} Subscription Plans.")
    print(f"Loaded {len(DISCOUNT_RULES)} Discount Governance Rules.")
    print(f"Loaded {len(APPROVAL_CHAINS)} Approval Chains.")
    print(f"Loaded {len(CUSTOMERS_DATA)} Mumbai Enterprise Customer Accounts.")
